name: project-specific-workflow

on:
  push:
#    branches: [main]
    paths-ignore:
      - 'deploy/**'
  pull_request:
#    branches: [main]
  workflow_dispatch:
    inputs:
      approve-release:
        description: 'Release to Jfrog'
        required: true
        default: 'true'
jobs:
  show-caller-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  invoke-workflow:
    uses: michaely-ln/reusable_workflow/.github/workflows/awesome-reusable-workflow.yml@main
